version: '3'
services:
  graphqlapi:
    build: .
    ports:
      - "4000:4000"
    links:
      - redis
    env_file:
      - production.env
  redis:
    image: "redis:latest"
    command: "redis-server --requirepass 9d13d2b1e6742c194349a22f66543417"
    ports:
      - "6379:6379"