version: '3'
services:
  api:
    build: .
    ports:
      - "80:80"
      - "443:443"
    links:
      - redis
    env_file:
      - production.env
    # logging:
    #   driver: awslogs
    #   options: 
    #     awslogs-group: hotminute-api
    #     awslogs-region: us-west-2
    #     awslogs-stream-prefix: api
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    # logging:
    #   driver: awslogs
    #   options: 
    #     awslogs-group: hotminute-api
    #     awslogs-region: us-west-2
    #     awslogs-stream-prefix: redis
